"""initial tables

Revision ID: 63db08e57482
Revises: 
Create Date: 2026-08-22 15:32:49.598860
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '63db08e57482'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('availability_windows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resource_type', sa.String(length=16), nullable=False),
    sa.Column('resource_id', sa.String(length=40), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.String(length=8), nullable=False),
    sa.Column('end_time', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_availability_windows_resource_id'), 'availability_windows', ['resource_id'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('priority_tier', sa.String(length=16), nullable=False),
    sa.Column('cgpa_cutoff', sa.Float(), nullable=False),
    sa.Column('interview_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('panel_count', sa.Integer(), nullable=False),
    sa.Column('available_days', sa.JSON(), nullable=False),
    sa.Column('availability_windows', sa.JSON(), nullable=False),
    sa.Column('delayed_until', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disruptions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=40), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('schedule_version_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disruptions_entity_id'), 'disruptions', ['entity_id'], unique=False)
    op.create_table('rooms',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_versions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=256), nullable=False),
    sa.Column('previous_version_id', sa.String(length=32), nullable=True),
    sa.Column('solver_status', sa.String(length=16), nullable=False),
    sa.Column('schedule_status', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('cgpa', sa.Float(), nullable=False),
    sa.Column('branch', sa.String(length=16), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('panels',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('company_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shortlists',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('student_id', sa.String(length=32), nullable=False),
    sa.Column('company_id', sa.String(length=32), nullable=False),
    sa.Column('shortlisted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interviews',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('schedule_version_id', sa.String(length=32), nullable=False),
    sa.Column('student_id', sa.String(length=32), nullable=False),
    sa.Column('company_id', sa.String(length=32), nullable=False),
    sa.Column('room_id', sa.String(length=32), nullable=True),
    sa.Column('panel_id', sa.String(length=40), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.String(length=8), nullable=True),
    sa.Column('end_time', sa.String(length=8), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['panel_id'], ['panels.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['schedule_version_id'], ['schedule_versions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id', 'schedule_version_id')
    )
    op.create_index(op.f('ix_interviews_company_id'), 'interviews', ['company_id'], unique=False)
    op.create_index(op.f('ix_interviews_schedule_version_id'), 'interviews', ['schedule_version_id'], unique=False)
    op.create_index(op.f('ix_interviews_student_id'), 'interviews', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interviews_student_id'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_schedule_version_id'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_company_id'), table_name='interviews')
    op.drop_table('interviews')
    op.drop_table('shortlists')
    op.drop_table('panels')
    op.drop_table('students')
    op.drop_table('schedule_versions')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_disruptions_entity_id'), table_name='disruptions')
    op.drop_table('disruptions')
    op.drop_table('companies')
    op.drop_index(op.f('ix_availability_windows_resource_id'), table_name='availability_windows')
    op.drop_table('availability_windows')
    # ### end Alembic commands ###
